<?php

return [
    'footer_sublinks' => 'nullable|array',
    'footer_links_1' => 'nullable|array',
    'footer_links_2' => 'nullable|array',
    'footer_links_3' => 'nullable|array',
    'desc_footer' => 'nullable|string',
    'record_connection' => 'nullable|string',
    'discord_embed_enable' => 'nullable|string',
    'discord_embed_id' => 'nullable|string',
    'mount_offer_enable' => 'nullable|string',
    'mount_offer_name' => 'nullable|string',
    'mount_offer_link' => 'nullable|string',
    'mount_offer_link_type' => 'nullable|string',
    'mount_offer_price' => 'nullable|string',
    'mount_offer_price_reduction' => 'nullable|string',
    'mount_offer_end_date' => 'nullable|string',
    'vote_award_1' => 'nullable|string',
    'vote_award_2' => 'nullable|string',
    'vote_award_3' => 'nullable|string',
    'vote_award_4' => 'nullable|string',
    'vote_award_5' => 'nullable|string',
    'vote_award_all' => 'nullable|string',
    'title_header_link_left' => 'nullable|string',
    'subtitle_header_link_left' => 'nullable|string',
    'img_header_link_left' => 'nullable|string',
    'link_header_link_left' => 'nullable|string',
    'title_header_link_right' => 'nullable|string',
    'subtitle_header_link_right' => 'nullable|string',
    'img_header_link_right' => 'nullable|string',
    'link_header_link_right' => 'nullable|string',
];
